<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Process\Module'                        => __DIR__ . '/Module.php',
    'Process\Controller\Index' => __DIR__ . '/src/Process/Controller/IndexController.php',
    'ZendSkeletonModuleTest\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'                => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);